-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO sell.ecommerce_sources(source, comment) values ('SHOPIFY', 'Shopify'), ('CREATEONE', 'Orders directly from create.ONE');
