-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "infraestructure"."bridge_sku_one_counter" add column "order_line_item_id" text
--  null;
