deployment:
  type: "res_long_running_service"
  replicas: 1
  servicePort: 5000
  ingressType: "public"
  env:
    RES_APP_NAME: "s3url-signer"
    HASURA_GRAPHQL_API_URL: "https://hasura-dev.resmagic.io/v1/graphql"
    RES_TEAM: "dxa"
