deployment:
  type: "res_long_running_service"
  name: "piece-classifier"
  replicas: 1
  servicePort: 5000
  ingressType: "public"
  env:
    RES_SECRET_NAME: res-data-dev
    #TODO - it can be convenient to bulk import secrets but you may want to control defaults
    SECRET_IMPORT_TYPE: not-exists
