apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: return-reason-clustering-cron
spec:
  schedule: "0 0 * * 1"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"      
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: return-reason-clustering
