deployment:
  type: "res_long_running_service"
  replicas: 1
  servicePort: 5000
  ingressType: "public"
  memory: 1G
  env:
    RES_APP_NAME: "platform-change-events-processor"
    RES_NAMESPACE: "res-platform"
    HASURA_GRAPHQL_API_URL: "https://hasura-dev.resmagic.io/v1/graphql"
