deployment:
  type: "res_long_running_service"
  replicas: 2
  servicePort: 5000
  ingressType: "public"
  env:
    RES_APP_NAME: "platform-change-events-processor"
    RES_NAMESPACE: "res-platform"
    HASURA_GRAPHQL_API_URL: "https://hasura.resmagic.io/v1/graphql"
    RES_TEAM: "dxa"