apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: zucc-meta-data-integration-cron
spec:
  schedule: "0 4,16 * * *"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"      
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: zucc-meta-data-integration
