apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: zucc-meta-data-integration
spec:
  entrypoint: zucc-meta-data-integration
  arguments:
    parameters:
    # Sync type can be overridden to perform full or test syncs
    - name: sync_type
      value: "incremental"
    - name: dev_override
      value: "" # Can be used to enable running the app in a dev environment
    - name: single_account
      value: "none" # Can be used to run the app for a single ad account id     
    - name: included_steps
      value: "all" # Can be used to run the app for specific steps       
  templates:
  - name: zucc-meta-data-integration
    inputs:
      parameters:
      - name: sync_type
      - name: dev_override
    steps:
    # Setting up steps. Future steps to be added in future PRs        
    - - name: ad-accounts
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ad_accounts.py"
          - name: memory
            value: 256Mi
        continueOn:
          failed: true    
    - - name: campaigns
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/campaigns.py"
          - name: memory
            value: 256Mi
        continueOn:
          failed: true   
    - - name: ad-sets
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ad_sets.py"
          - name: memory
            value: 512Mi
        continueOn:
          failed: true                        
    - - name: ads
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ads.py"
          - name: memory
            value: 4096Mi   
        continueOn:
          failed: true                                
    - - name: ad-images
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ad_images.py"
          - name: memory
            value: 1024Mi   
        continueOn:
          failed: true                
    - - name: insights
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: single_account
            value: "{{workflow.parameters.single_account}}"            
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/insights.py"
          - name: memory
            value: 1024Mi                                                                                         
  - name: generic-step
    retryStrategy:
          limit: "3"
          retryPolicy: "Always" 
          backoff:
            duration: "10m"
            factor: "2"  
    inputs:
      parameters:
      - name: sync_type
      - name: dev_override      
      - name: single_account      
      - name: included_steps      
      - name: flow_name
      - name: memory
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests": { "memory": "{{inputs.parameters.memory}}" }, "limits":{ "memory": "{{inputs.parameters.memory}}" }}}]}'
    container:
      image: this-image
      command: [python]
      args: [ "{{inputs.parameters.flow_name}}", "{{inputs.parameters.sync_type}}", "{{inputs.parameters.dev_override}}", "{{inputs.parameters.single_account}}", "{{inputs.parameters.included_steps}}" ]
      envFrom:
       - configMapRef:
           name: res-data-env
 