-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "meta"."body_request_asset_annotations" add column "value2" text
--  null;
