-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sell"."orders" add column "revenue_share_percentage_wholesale" numeric
--  null;
