-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sell"."faceted_search_filters_collection" add column "created_at" timestamptz
--  null default now();
