mutation ($objects: [make_piece_instances_insert_input!]!) {
  insert_make_piece_instances(objects: $objects, on_conflict: {constraint: piece_instances_pkey, update_columns: [healing, metadata, one_number]}) {
    affected_rows
    returning {
      id
    }
  }
}
