metadata:
  name: example-ssm-vault-plugin-secret
  namespace: argocd
spec:
  destination:
    namespace: res-examples
    server: https://kubernetes.default.svc
  project: res-examples
  source:
    path: apps/res-examples/example-ssm-vault-plugin-secret/production
    repoURL: git@github.com:resonance/res-data-platform.git
    targetRevision: main
