apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: quickbooks-invoice-generator-cron
spec:
  schedule: "0 7 * * 1"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"      
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: true
  workflowSpec:
    workflowTemplateRef:
      name: quickbooks-invoice-generator