-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "meta"."pieces" add column "base_image_outline" jsonb
--  null default jsonb_build_object();
