apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../example-argo-dag

images:
  - name: this-image
    newName: 286292902993.dkr.ecr.us-east-1.amazonaws.com/res-data_development_example-argo-dag_res-examples
    newTag: latest