apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
  labels:
    app: {{ .Values.deployment.name }}
spec:
  {{- if ne .Values.global.environment "local" }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
  - port: {{ .Values.deployment.servicePort }}
    targetPort: backend-tcp
  selector:
    app: {{ .Values.deployment.name }}
    component: {{ .Values.deployment.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    component: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      component: {{ .Values.deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        component: {{ .Values.deployment.name }}
    spec:
      initContainers:
      - name: {{ .Values.deployment.name }}-flyway
        image: {{ .Values.global.ecrRepo }}/res-data_{{ .Values.global.environment }}_{{ .Values.deployment.name }}_{{ .Values.deployment.folder }}:{{ .Values.commitHash }}
        env:
          - name: POSTGRES_HOST
            value: "{{ .Values.deployment.name }}-postgresql.{{ .Values.deployment.folder }}.svc.cluster.local"
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.postgresqlUsername }}
          - name: POSTGRES_PW
            value: {{ .Values.postgresql.postgresqlPassword }}
          - name: POSTGRES_PORT
            value: "{{ .Values.postgresql.service.port }}"
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: FLYWAY_EDITION
            value: "community"
        args: ["-url=jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)", "-user=$(POSTGRES_USER)", "-password=$(POSTGRES_PW)", "-connectRetries=100", "migrate"]
      containers:
      - name: {{ .Values.deployment.name }}
        image: 286292902993.dkr.ecr.us-east-1.amazonaws.com/postgraphile:v4.11.0
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_HOST
            value: "{{ .Values.deployment.name }}-postgresql.{{ .Values.deployment.folder }}.svc.cluster.local"
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.postgresqlUsername }}
          - name: POSTGRES_PW
            value: {{ .Values.postgresql.postgresqlPassword }}
          - name: POSTGRES_PORT
            value: "{{ .Values.postgresql.service.port }}"
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: POSTGRES_SCHEMA
            value: {{ .Values.deployment.postgresSchema }}
        ports:
        - containerPort: {{ .Values.deployment.servicePort }}
          name: backend-tcp
        args: ["--connection", "postgres://$(POSTGRES_USER):$(POSTGRES_PW)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)", "--schema", "$(POSTGRES_SCHEMA)", "--watch", "--retry-on-init-fail", "--enhance-graphiql"]