apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  # NB: this is the name of the target secret!!
  name: example-sops-secret-files
files:
  - secret-creds.enc.env
  - secret-creds.enc.properties
  # can also include the secret for ksops, fwiw:
  - secret.enc.yaml
env:
  - secret-creds.enc.env
type: Opaque
# merge or replace behavior is specified on the generator
behavior: replace
