apiVersion: v1
data:
    FOO: ENC[AES256_GCM,data:LxkofpwY4LU=,iv:EBCnW/dQSO4+M/E1l3c5FdQUPp9thPtatlG4lAEJ31Y=,tag:zQbfq+LWU2EnIJ/8CCf/NQ==,type:str]
kind: Secret
metadata:
    name: example-sops-secret
    annotations:
        kustomize.config.k8s.io/behavior: merge
stringData:
    BAR: ENC[AES256_GCM,data:6b8ikg==,iv:qaEyHZD9O0/DlMSPdXseuB7WHac99EBDbEm8m97O1I4=,tag:Zm7Mnc8PVryN3bjKbEkRVw==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:286292902993:key/8dc23836-ab89-4581-a981-14c3c646c1ba
          role: arn:aws:iam::286292902993:role/argocd-sa-role
          created_at: "2022-07-16T16:24:50Z"
          enc: AQICAHgPdAvulU5/aXIXPDm3XYIFQRuoxDaKt3ktMkWdqy/j5wHUQUV/rY7HMfI63K0Vsy9nAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGE8g9/piZGJfKHZNAgEQgDsaK9ycAX1mmkBBcemO9DSLNXNu3R8QwvysMSU7wKhoSJ4z1QF59foKuD4ublpdkbIGHJsS5h9BEBHa1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-16T16:24:50Z"
    mac: ENC[AES256_GCM,data:EAGj/CIbAIz7RtliwIdXqyv7OMVKHDIv+VI6SzEisaTbHqEY4Zr3fMLQwBbkqAgJWFUU13HrgMWArwwNjRa5wzndjAQRdqB63UXYLmS5pytOFwGINQm8iSMnjg0dhri//ojbc20OinsY4Cb6l555iHHzXNyBTcBvapDUl5/6xFU=,iv:m7/o9lT8p+7XFLf2BeZP+XsH/j5W3gmCdml4eJpXtMA=,tag:h/eSFrTD5CcBa2+RhzWKEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
