-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sell"."transactions" add column "stripe_charge_id" text
--  not null unique;
