apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: zendesk-data-integration
spec:
  entrypoint: zendesk-data-integration
  arguments:
    parameters:
    # Sync type can be overridden to perform full or test syncs
    - name: sync_type
      value: "incremental"
    - name: dev_override
      value: "" # Can be used to enable running the app in a dev environment
    - name: included_steps
      value: "all" # Can be used to run the app for specific steps      
  templates:
  - name: zendesk-data-integration
    inputs:
      parameters:
      - name: sync_type
      - name: dev_override
      - name: included_steps
    steps:         
    - - name: ticket-events
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ticket_events.py"
          - name: memory
            value: 4096Mi
        continueOn:
          failed: true    
    - - name: ticket-metric-events
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/ticket_metric_events.py"
          - name: memory
            value: 4096Mi
        continueOn:
          failed: true   
    - - name: tickets
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/tickets.py"
          - name: memory
            value: 2048Mi
        continueOn:
          failed: true                        
    - - name: users
        template: generic-step
        arguments:
          parameters:
          - name: sync_type
            value: "{{workflow.parameters.sync_type}}"
          - name: dev_override
            value: "{{workflow.parameters.dev_override}}"
          - name: included_steps
            value: "{{workflow.parameters.included_steps}}"            
          - name: flow_name
            value: "/app/src/users.py"
          - name: memory
            value: 512Mi                                                                                                 
  - name: generic-step
    retryStrategy:
          limit: "3"
          retryPolicy: "Always" 
          backoff:
            duration: "10m"
            factor: "2"  
    inputs:
      parameters:
      - name: sync_type
      - name: dev_override      
      - name: included_steps      
      - name: flow_name
      - name: memory
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests": { "memory": "{{inputs.parameters.memory}}" }, "limits":{ "memory": "{{inputs.parameters.memory}}" }}}]}'
    container:
      image: this-image
      command: [python]
      args: [ "{{inputs.parameters.flow_name}}", "{{inputs.parameters.sync_type}}", "{{inputs.parameters.dev_override}}", "{{inputs.parameters.included_steps}}" ]
      envFrom:
       - configMapRef:
           name: res-data-env
 