deployment:
  type: "res_workflow"
  cron:
    enable: false
    schedule: "0 0 * * *"
  env:
    BACKFILL: 0
    SHORTCUT_HOST: https://api.app.shortcut.com
    DRY_RUN: 1
    RES_TEAM: "iamcurious"
  command: python
  args:
    - /app/src/main.py
