apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: example-argo-dag-cron
spec:
  schedule: "0 5 * * *"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"      
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: example-argo-dag
