apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-argo-dag
spec:
  entrypoint: example-argo-dag
  arguments:
    parameters:
    - name: event
      value: "{}"
  templates:
  - name: example-argo-dag
    inputs:
      parameters:
      - name: event
    steps:
    - - name: generate-names
        template: generic-step
        arguments:
          parameters:
          # These parameters can be overridden by a developer in the Argo UI
          - name: event
            value: "{{workflow.parameters.event}}"
          # This is the name of the python script you want to run for this step
          - name: flow_name
            value: "/app/src/01_generate_names.py"
          # We can set memory higher for intensive tasks
          - name: memory
            value: 128Mi
    - - name: hello-worlds
        template: generic-step
        arguments:
          parameters:
          - name: event
            # You can access the items from the withParam list below like this:
            value: "{{item}}"
          - name: flow_name
            value: "/app/src/02_hello_worlds.py"
          - name: memory
            value: 256Mi
        # This "withParam" tells Argo to generate a parallel step for each item in the list found in "dump"
        withParam: "{{steps.generate-names.outputs.parameters.dump}}"
  - name: generic-step
    retryStrategy:
          limit: "2"
          retryPolicy: "OnFailure" 
          backoff:
            duration: "3m"  
    inputs:
      parameters:
      - name: event
      - name: flow_name
      - name: memory
    outputs:
      parameters:
        - name: dump
          valueFrom:
            path: /app/dump.txt
    podSpecPatch: '{"containers":[{"name":"main", "resources":{"requests": { "memory": "{{inputs.parameters.memory}}" }, "limits":{ "memory": "{{inputs.parameters.memory}}" }}}]}'
    container:
      # This container image will be replaced during CI with the Dockerfile you included in this folder
      image: this-image
      command: [python]
      args: [ "{{inputs.parameters.flow_name}}", "{{inputs.parameters.event}}" ]
      envFrom:
       - configMapRef:
           name: res-data-env
