-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "make"."one_pieces_costs" add column "metadata" jsonb
--  null default jsonb_build_object();
