-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "meta"."bodies" add column "fusing_pieces" jsonb
--  not null default jsonb_build_object();
