# Unencrypted secret that will be merged onto
apiVersion: v1
data:
  NOT_ENCRYPTED: dGhpcyBpcyBwbGFpbnRleHQgdGhhdCB3aWxsIHNob3cgdXAgaW4gdGhlIGVudg==
  # decoded:
  # NOT_ENCRYPTED: this is plaintext that will show up in the env
kind: Secret
metadata:
  name: example-sops-secret
type: Opaque
---
# Empty secret that will be replaced
apiVersion: v1
data:
  unencrypted-file.txt: VGhpcyBmaWxlIHdpbGwgbm90IGJlCnByZXNlbnQgaW4gdGhlIGZpbmFsCnNlY3JldCBvciB0aGUgbW91bnRlZAp2b2x1bWUu
  # decoded:
  # unencrypted-file.txt: |-
  #   This file will not be
  #   present in the final
  #   secret or the mounted
  #   volume.
kind: Secret
metadata:
  name: example-sops-secret-files
type: Opaque
