global:
  environment: development
  awsAccountId: 286292902993
  adminEmail: techpirates@resonance.nyc
  publicSubnet1: subnet-0bcb8ea8c2c3a6d87
  publicSubnet2: subnet-0ca188104a371bce8
  publicSubnet3: subnet-0e07a78a1c0f5bbb8
  privateSubnet1: subnet-00a69e118e19b8030
  privateSubnet2: subnet-0c603827af95757b6
  privateSubnet3: subnet-0bf3c0c43bb9fbd2e
  ecrRepo: 286292902993.dkr.ecr.us-east-1.amazonaws.com
  commitHash: default

deployment:
  folder: default
  name: default

baseEnvs:
  RES_ENV: development
  RES_CLUSTER: res-primary-cluster-dev
  KAFKA_SCHEMA_REGISTRY_URL: kafka-schema-registry-cp-schema-registry.kafka-schema-registry.svc.cluster.local:8081
  KAFKA_BROKERS: b-2.res-primary-dev.0hn5z0.c13.kafka.us-east-1.amazonaws.com:9094,b-3.res-primary-dev.0hn5z0.c13.kafka.us-east-1.amazonaws.com:9094,b-1.res-primary-dev.0hn5z0.c13.kafka.us-east-1.amazonaws.com:9094
  KAFKA_CONNECT_URL: kafka-connect-cp-kafka-connect.kafka-connect.svc.cluster.local:8083
  KAFKA_KGATEWAY_URL: kgateway-service.res-infrastructure.svc.cluster.local:5000
  STATSD_HOST: statsd-exporter-prometheus-statsd-exporter.statsd-exporter.svc.cluster.local
  GRAPHQL_API_URL: https://api.resmagic.io/graphql
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  MONGODB_HOST: resmagic.fahv4.mongodb.net
  SNOWFLAKE_ACCOUNT: jk18804.us-east-1
  ARGO_SERVER: http://argo-server.argo.svc.cluster.local:2746
  LOOKERSDK_BASE_URL: https://resonance.looker.com:19999
  LOOKERSDK_VERIFY_SSL: true
  RES_CONNECT_URL: https://datadev.resmagic.io/res-connect
  RES_DATA_BUCKET: res-data-development
  DGRAPH_ALPHA: http://dgraph-dgraph-alpha.dgraph.svc.cluster.local:8080
  COGNITO_USERPOOL_ID: us-east-1_Iq9hu7e1j
  COGNITO_APP_CLIENT_ID: 4i6fnohp1um59dj2vlvhfma8tn
  REDIS_HOST: redis-master.redis.svc.cluster.local
  PRIMARY_RDS_ENDPOINT: res-primary-dev.c6mvudtydvki.us-east-1.rds.amazonaws.com
  HASURA_GRAPHQL_API_URL: "https://hasura-dev.resmagic.io/v1/graphql"
  WEAVIATE_URL: "http://weaviate.weaviate.svc.cluster.local"
