apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: shopify-data-integration-cron
spec:
  schedule: "0 5,17 * * *"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"      
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    workflowTemplateRef:
      name: shopify-data-integration
