WITH mongo_streams_monitor AS (
    SELECT TABLE_NAME, ROW_COUNT, LAST_ALTERED
    FROM "SNOWFLAKE"."ACCOUNT_USAGE"."TABLES"
    WHERE TABLE_SCHEMA = 'IAMCURIOUS_PRODUCTION'
    AND TABLE_NAME LIKE 'MONGO_RESMAGIC%'
    AND DELETED IS NULL
    LIMIT 100
)
SELECT
    TABLE_NAME,
    DATEDIFF(minute,LAST_ALTERED,CURRENT_TIMESTAMP) as DATEDIFF
FROM mongo_streams_monitor