apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-ssm-vault-plugin-secret-secrets
  namespace: argocd
spec:
  destination:
    namespace: res-examples
    server: https://kubernetes.default.svc
  project: res-examples
  source:
    path: apps/res-examples/example-ssm-vault-plugin-secret/production/secrets
    repoURL: git@github.com:resonance/res-data-platform.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-ssm
  syncPolicy:
    automated: {}