apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

commonLabels:
  env: production

commonAnnotations:
  env: production

patches:
  - path: config.yaml
    target:
      version: v1
      kind: ConfigMap
      name: example-config
      labelSelector: "resonance.nyc/app=example"