kind: Secret
apiVersion: v1
metadata:
  name: hasura-secret
  annotations: {}
type: Opaque
stringData:
  S3_URL_SIGNER_ENDPOINT: http://s3url-signer-service.res-create.svc.cluster.local:5000/graphql
  NULL_HYPOTHESIS_ENDPOINT: http://null-hypothesis-service.res-infrastructure.svc.cluster.local:5000/event-trigger
  GRAPHQL_API_URL: https://api.resmagic.io/graphql
  GRAPHQL_API_KEY: <path:GRAPH_API_KEY#production>
  HASURA_GRAPHQL_ADMIN_SECRET: <path:HASURA_SECRET_DATA#production | jsonPath {.HASURA_GRAPHQL_ADMIN_SECRET}>
  HASURA_GRAPHQL_DATABASE_URL: <path:HASURA_SECRET_DATA#production | jsonPath {.HASURA_GRAPHQL_DATABASE_URL}>
  HASURA_GRAPHQL_METADATA_DATABASE_URL: <path:HASURA_SECRET_DATA#production | jsonPath {.HASURA_GRAPHQL_METADATA_DATABASE_URL}>
