-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sell"."ecommerce_collections" add column "publication_metadata" json
--  null;
