{
 "title": "Flow overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "node" } },
   { "name": "data_group", "query": { "query": "data_group" } },
   { "name": "flow", "query": { "query": "flow" } }
  ]
 },
 "panels": [
  {
   "title": "Airtable etl flow events",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flows{flow=\"etl-airtable-v0\"})",
     "legendFormat": "Airtable etl flow events"
    }
   ]
  },
  {
   "title": "Nesting events",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flows{flow=\"dxa-printfile-expv2\"})",
     "legendFormat": "Nesting events"
    }
   ]
  },
  {
   "title": "Watched flow nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flows" }
   ]
  },
  {
   "title": "Watched flows",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flows", "legendFormat": "{{node}}" }
   ]
  }
 ]
}