{
 "title": "Webhooks",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Print assets messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_connect__tblwDQtDckvHKXO4w_webhook_messages[5m])",
     "legendFormat": "Print assets"
    }
   ]
  },
  {
   "title": "Print asset handler errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(res_connect__tblwDQtDckvHKXO4w_webhook_handler_errors[5m])",
     "legendFormat": "Print assets"
    }
   ]
  },
  {
   "title": "Rolls - messages rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_connect__tblSYU8a71UgbQve4_webhook_messages[5m])",
     "legendFormat": "Rolls message rate"
    }
   ]
  },
  {
   "title": "Rolls handler errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(res_connect__tblSYU8a71UgbQve4_webhook_handler_errors[5m])",
     "legendFormat": "Rolls errors"
    }
   ]
  },
  {
   "title": "Prod requests messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_connect__tblptyuWfGEUJWwKk_webhook_messages[5m])",
     "legendFormat": "Prod requests"
    }
   ]
  },
  {
   "title": "Prod requests errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(res_connect__tblptyuWfGEUJWwKk_webhook_handler_errors[5m])",
     "legendFormat": "Prod requests"
    }
   ]
  },
  {
   "title": "Order linte items",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_connect__tblUcI0VyLs7070yI_webhook_messages[5m])",
     "legendFormat": "Fulf. Order Line Items"
    }
   ]
  },
  {
   "title": "Order line items handler errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(res_connect__tblUcI0VyLs7070yI_webhook_handler_errors[5m])",
     "legendFormat": "Order line items"
    }
   ]
  },
  {
   "title": "Recent webhook messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(res_connect__tbl3pELGlqI7rbylr_webhook_messages[5m])",
     "legendFormat": "IAC Dashboard"
    },
    {
     "expr": "rate(res_connect__tblDBazjzsT7otfye_webhook_messages[5m])",
     "legendFormat": "Vendors"
    },
    {
     "expr": "rate(None__tblUcI0VyLs7070yI_webhook_messages[5m])",
     "legendFormat": "Order Line Items"
    },
    {
     "expr": "rate(None__tblhCz4t3QVjxWOpv_webhook_messages[5m])",
     "legendFormat": "Inv Delta additions"
    },
    {
     "expr": "rate(None__tblptyuWfGEUJWwKk_webhook_messages[5m])",
     "legendFormat": "Prod requests"
    }
   ]
  }
 ]
}