apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

generators:
  - ./goabout-sops-secret-generator.yaml
  - ./ksops-secret-generator.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: example-sops-secret
      spec:
        template:
          spec:
            containers:
            - name: example-sops-secret
              env:
                - name: RES_ENV
                  value: development
