deployment:
  type: "res_long_running_service"
  replicas: 1
  servicePort: 5000
  ingressType: "public"
  env:
    # BRAND_LAYER_ID: "recToR13fVcplQk3X"
    # SHOPIFY_DATASOURCE_ID: "recci2gc1iFBYXHgV"
    TECH_PIRATES_TEST_CUSTOMER_ID: "cus_Ncdum4p5b5Jphd"
