name: close-infra-pr
on:
  pull_request:
    types: [closed]

jobs:
  #https://github.com/orgs/community/discussions/27071
  clean-up-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
      - name: Checkout Infra
        uses: actions/checkout@v4
        with:
          repository: resonance/res-data-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
          path: res-data-infra
          ref: main
      - name: Close infra PR after source merged
        run: |
          branch=sourced-pr-${{ fromJson(steps.get_pr_data.outputs.result).number }}
          cd res-data-infra
          git config --global user.email "techpirates@resonance.nyc"
          git config --global user.name "CI Bot"
          git config --global credential.helper cache
          git checkout -b $branch

          echo "Using the branch ref $branch"

          gh auth login --with-token <<< "${{ secrets.INFRA_TOKEN }}"
          prs=$(gh pr list -B main -H $branch)  
          if ((${#prs[@]} > 0 && ${#prs[0]} != 0 )); then
            echo "Closing PR on branch $branch"
            gh pr close $branch
          else
            echo "Did not match $branch"
          fi

  clean-up-closed-pr:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged
      - name: Checkout infra
        uses: actions/checkout@v4
        with:
          repository: resonance/res-data-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
          path: res-data-infra
          ref: main
      - name: Close infra PR after source close
        run: |
          branch=sourced-pr-${{  github.event.pull_request.number }}
          cd res-data-infra
          git config --global user.email "techpirates@resonance.nyc"
          git config --global user.name "CI Bot"
          git config --global credential.helper cache
          git checkout -b $branch

          echo "Using the branch ref $branch"

          gh auth login --with-token <<< "${{ secrets.INFRA_TOKEN }}"
          prs=$(gh pr list -B main -H -$branch)  
          if ((${#prs[@]} > 0 && ${#prs[0]} != 0 )); then
            echo "Closing PR on branch $branch"
            gh pr close $branch
          else
            echo "Did not match $branch"
          fi

          #in this case we should probably delete the remote branch too but on merge the target is configured to purge
