{
 "title": "Webhooks",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Order Line items Webhook Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_data__tblUcI0VyLs7070yI_webhook_messages[5m])",
     "legendFormat": "Order Line Items"
    },
    { "expr": "res_data__tbl" }
   ]
  },
  {
   "title": "DELTAS.additions Webhook Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_data__tblhCz4t3QVjxWOpv_webhook_messages[5m])",
     "legendFormat": "DELTAS.additions"
    }
   ]
  },
  {
   "title": "Rolls Webhook Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_data__tblSYU8a71UgbQve4_webhook_messages[5m])",
     "legendFormat": "Roll Messages"
    }
   ]
  },
  {
   "title": "Purchasing Requests Webhook Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_data__tblc4lat36qr4UowZ_webhook_messages[5m])",
     "legendFormat": "Purchasing Requests"
    }
   ]
  },
  {
   "title": "Webhook messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(res_data__webhook_messages[5m])",
     "legendFormat": "all webhooks messages"
    }
   ]
  }
 ]
}