orders_table_create = """
CREATE TABLE IF NOT EXISTS IAMCURIOUS_{env}.SHOPIFY_ORDERS (
	id NUMBER(38,0),
	admin_graphql_api_id VARCHAR(),
	app_id NUMBER(38,0),
	browser_ip VARCHAR(),
	buyer_accepts_marketing BOOLEAN,
	cancel_reason VARCHAR(),
	cancelled_at VARCHAR(),
	cart_token VARCHAR(),
	checkout_id NUMBER(38,0),
	checkout_token VARCHAR(),
	client_details VARIANT,
	closed_at VARCHAR(),
	confirmed BOOLEAN,
	contact_email VARCHAR(),
	created_at VARCHAR(),
	currency VARCHAR(),
	current_subtotal_price VARCHAR(),
	current_subtotal_price_set VARIANT,
	current_total_discounts VARCHAR(),
	current_total_discounts_set VARIANT,
	current_total_duties_set VARCHAR(),
	current_total_price VARCHAR(),
	current_total_price_set VARIANT,
	current_total_tax VARCHAR(),
	current_total_tax_set VARIANT,
	customer_locale VARCHAR(),
	device_id VARCHAR(),
	discount_codes VARIANT,
	email VARCHAR(),
	estimated_taxes BOOLEAN,
	financial_status VARCHAR(),
	fulfillment_status VARCHAR(),
	gateway VARCHAR(),
	landing_site VARCHAR(),
	landing_site_ref VARCHAR(),
	location_id VARCHAR(),
	name VARCHAR(),
	note VARCHAR(),
	note_attributes VARIANT,
	number NUMBER(38,0),
	order_number NUMBER(38,0),
	order_status_url VARCHAR(),
	original_total_duties_set VARCHAR(),
	payment_gateway_names VARIANT,
	phone VARCHAR(),
	presentment_currency VARCHAR(),
	processed_at VARCHAR(),
	processing_method VARCHAR(),
	reference VARCHAR(),
	referring_site VARCHAR(),
	source_identifier VARCHAR(),
	source_name VARCHAR(),
	source_url VARCHAR(),
	subtotal_price VARCHAR(),
	subtotal_price_set VARIANT,
	tags VARCHAR(),
	tax_lines VARIANT,
	taxes_included BOOLEAN,
	test BOOLEAN,
	token VARCHAR(),
	total_discounts VARCHAR(),
	total_discounts_set VARIANT,
	total_line_items_price VARCHAR(),
	total_line_items_price_set VARIANT,
	total_outstanding VARCHAR(),
	total_price VARCHAR(),
	total_price_set VARIANT,
	total_price_usd VARCHAR(),
	total_shipping_price_set VARIANT,
	total_tax VARCHAR(),
	total_tax_set VARIANT,
	total_tip_received VARCHAR(),
	total_weight NUMBER(38,0),
	updated_at VARCHAR(),
	user_id VARCHAR(),
	billing_address VARIANT,
	customer VARIANT,
	discount_applications VARIANT,
	fulfillments VARIANT,
	line_items VARIANT,
	payment_terms VARCHAR(),
	refunds VARIANT,
	shipping_address VARIANT,
	shipping_lines VARIANT,
	brand_code VARCHAR()
);
"""
orders_upsert = """
MERGE INTO IAMCURIOUS_{env}.SHOPIFY_ORDERS t1
    USING IAMCURIOUS_{env}_STAGING.SHOPIFY_ORDERS_temp t2
    ON t1.id = t2.data:id::varchar
    when matched then update set 	t1.id = t2.data:id::NUMBER(38,0),
	t1.admin_graphql_api_id = t2.data:admin_graphql_api_id::VARCHAR,
	t1.app_id = t2.data:app_id::NUMBER(38,0),
	t1.browser_ip = t2.data:browser_ip::VARCHAR,
	t1.buyer_accepts_marketing = t2.data:buyer_accepts_marketing::BOOLEAN,
	t1.cancel_reason = t2.data:cancel_reason::VARCHAR,
	t1.cancelled_at = t2.data:cancelled_at::VARCHAR,
	t1.cart_token = t2.data:cart_token::VARCHAR,
	t1.checkout_id = t2.data:checkout_id::NUMBER(38,0),
	t1.checkout_token = t2.data:checkout_token::VARCHAR,
	t1.client_details = t2.data:client_details::VARIANT,
	t1.closed_at = t2.data:closed_at::VARCHAR,
	t1.confirmed = t2.data:confirmed::BOOLEAN,
	t1.contact_email = t2.data:contact_email::VARCHAR,
	t1.created_at = t2.data:created_at::VARCHAR,
	t1.currency = t2.data:currency::VARCHAR,
	t1.current_subtotal_price = t2.data:current_subtotal_price::VARCHAR,
	t1.current_subtotal_price_set = t2.data:current_subtotal_price_set::VARIANT,
	t1.current_total_discounts = t2.data:current_total_discounts::VARCHAR,
	t1.current_total_discounts_set = t2.data:current_total_discounts_set::VARIANT,
	t1.current_total_duties_set = t2.data:current_total_duties_set::VARCHAR,
	t1.current_total_price = t2.data:current_total_price::VARCHAR,
	t1.current_total_price_set = t2.data:current_total_price_set::VARIANT,
	t1.current_total_tax = t2.data:current_total_tax::VARCHAR,
	t1.current_total_tax_set = t2.data:current_total_tax_set::VARIANT,
	t1.customer_locale = t2.data:customer_locale::VARCHAR,
	t1.device_id = t2.data:device_id::VARCHAR,
	t1.discount_codes = t2.data:discount_codes::VARIANT,
	t1.email = t2.data:email::VARCHAR,
	t1.estimated_taxes = t2.data:estimated_taxes::BOOLEAN,
	t1.financial_status = t2.data:financial_status::VARCHAR,
	t1.fulfillment_status = t2.data:fulfillment_status::VARCHAR,
	t1.gateway = t2.data:gateway::VARCHAR,
	t1.landing_site = t2.data:landing_site::VARCHAR,
	t1.landing_site_ref = t2.data:landing_site_ref::VARCHAR,
	t1.location_id = t2.data:location_id::VARCHAR,
	t1.name = t2.data:name::VARCHAR,
	t1.note = t2.data:note::VARCHAR,
	t1.note_attributes = t2.data:note_attributes::VARIANT,
	t1.number = t2.data:number::NUMBER(38,0),
	t1.order_number = t2.data:order_number::NUMBER(38,0),
	t1.order_status_url = t2.data:order_status_url::VARCHAR,
	t1.original_total_duties_set = t2.data:original_total_duties_set::VARCHAR,
	t1.payment_gateway_names = t2.data:payment_gateway_names::VARIANT,
	t1.phone = t2.data:phone::VARCHAR,
	t1.presentment_currency = t2.data:presentment_currency::VARCHAR,
	t1.processed_at = t2.data:processed_at::VARCHAR,
	t1.processing_method = t2.data:processing_method::VARCHAR,
	t1.reference = t2.data:reference::VARCHAR,
	t1.referring_site = t2.data:referring_site::VARCHAR,
	t1.source_identifier = t2.data:source_identifier::VARCHAR,
	t1.source_name = t2.data:source_name::VARCHAR,
	t1.source_url = t2.data:source_url::VARCHAR,
	t1.subtotal_price = t2.data:subtotal_price::VARCHAR,
	t1.subtotal_price_set = t2.data:subtotal_price_set::VARIANT,
	t1.tags = t2.data:tags::VARCHAR,
	t1.tax_lines = t2.data:tax_lines::VARIANT,
	t1.taxes_included = t2.data:taxes_included::BOOLEAN,
	t1.test = t2.data:test::BOOLEAN,
	t1.token = t2.data:token::VARCHAR,
	t1.total_discounts = t2.data:total_discounts::VARCHAR,
	t1.total_discounts_set = t2.data:total_discounts_set::VARIANT,
	t1.total_line_items_price = t2.data:total_line_items_price::VARCHAR,
	t1.total_line_items_price_set = t2.data:total_line_items_price_set::VARIANT,
	t1.total_outstanding = t2.data:total_outstanding::VARCHAR,
	t1.total_price = t2.data:total_price::VARCHAR,
	t1.total_price_set = t2.data:total_price_set::VARIANT,
	t1.total_price_usd = t2.data:total_price_usd::VARCHAR,
	t1.total_shipping_price_set = t2.data:total_shipping_price_set::VARIANT,
	t1.total_tax = t2.data:total_tax::VARCHAR,
	t1.total_tax_set = t2.data:total_tax_set::VARIANT,
	t1.total_tip_received = t2.data:total_tip_received::VARCHAR,
	t1.total_weight = t2.data:total_weight::NUMBER(38,0),
	t1.updated_at = t2.data:updated_at::VARCHAR,
	t1.user_id = t2.data:user_id::VARCHAR,
	t1.billing_address = t2.data:billing_address::VARIANT,
	t1.customer = t2.data:customer::VARIANT,
	t1.discount_applications = t2.data:discount_applications::VARIANT,
	t1.fulfillments = t2.data:fulfillments::VARIANT,
	t1.line_items = t2.data:line_items::VARIANT,
	t1.payment_terms = t2.data:payment_terms::VARCHAR,
	t1.refunds = t2.data:refunds::VARIANT,
	t1.shipping_address = t2.data:shipping_address::VARIANT,
	t1.shipping_lines = t2.data:shipping_lines::VARIANT,
	t1.brand_code = t2.data:brand_code::VARCHAR
    when not matched then insert values (	t2.data:id::NUMBER(38,0),
	t2.data:admin_graphql_api_id::VARCHAR,
	t2.data:app_id::NUMBER(38,0),
	t2.data:browser_ip::VARCHAR,
	t2.data:buyer_accepts_marketing::BOOLEAN,
	t2.data:cancel_reason::VARCHAR,
	t2.data:cancelled_at::VARCHAR,
	t2.data:cart_token::VARCHAR,
	t2.data:checkout_id::NUMBER(38,0),
	t2.data:checkout_token::VARCHAR,
	t2.data:client_details::VARIANT,
	t2.data:closed_at::VARCHAR,
	t2.data:confirmed::BOOLEAN,
	t2.data:contact_email::VARCHAR,
	t2.data:created_at::VARCHAR,
	t2.data:currency::VARCHAR,
	t2.data:current_subtotal_price::VARCHAR,
	t2.data:current_subtotal_price_set::VARIANT,
	t2.data:current_total_discounts::VARCHAR,
	t2.data:current_total_discounts_set::VARIANT,
	t2.data:current_total_duties_set::VARCHAR,
	t2.data:current_total_price::VARCHAR,
	t2.data:current_total_price_set::VARIANT,
	t2.data:current_total_tax::VARCHAR,
	t2.data:current_total_tax_set::VARIANT,
	t2.data:customer_locale::VARCHAR,
	t2.data:device_id::VARCHAR,
	t2.data:discount_codes::VARIANT,
	t2.data:email::VARCHAR,
	t2.data:estimated_taxes::BOOLEAN,
	t2.data:financial_status::VARCHAR,
	t2.data:fulfillment_status::VARCHAR,
	t2.data:gateway::VARCHAR,
	t2.data:landing_site::VARCHAR,
	t2.data:landing_site_ref::VARCHAR,
	t2.data:location_id::VARCHAR,
	t2.data:name::VARCHAR,
	t2.data:note::VARCHAR,
	t2.data:note_attributes::VARIANT,
	t2.data:number::NUMBER(38,0),
	t2.data:order_number::NUMBER(38,0),
	t2.data:order_status_url::VARCHAR,
	t2.data:original_total_duties_set::VARCHAR,
	t2.data:payment_gateway_names::VARIANT,
	t2.data:phone::VARCHAR,
	t2.data:presentment_currency::VARCHAR,
	t2.data:processed_at::VARCHAR,
	t2.data:processing_method::VARCHAR,
	t2.data:reference::VARCHAR,
	t2.data:referring_site::VARCHAR,
	t2.data:source_identifier::VARCHAR,
	t2.data:source_name::VARCHAR,
	t2.data:source_url::VARCHAR,
	t2.data:subtotal_price::VARCHAR,
	t2.data:subtotal_price_set::VARIANT,
	t2.data:tags::VARCHAR,
	t2.data:tax_lines::VARIANT,
	t2.data:taxes_included::BOOLEAN,
	t2.data:test::BOOLEAN,
	t2.data:token::VARCHAR,
	t2.data:total_discounts::VARCHAR,
	t2.data:total_discounts_set::VARIANT,
	t2.data:total_line_items_price::VARCHAR,
	t2.data:total_line_items_price_set::VARIANT,
	t2.data:total_outstanding::VARCHAR,
	t2.data:total_price::VARCHAR,
	t2.data:total_price_set::VARIANT,
	t2.data:total_price_usd::VARCHAR,
	t2.data:total_shipping_price_set::VARIANT,
	t2.data:total_tax::VARCHAR,
	t2.data:total_tax_set::VARIANT,
	t2.data:total_tip_received::VARCHAR,
	t2.data:total_weight::NUMBER(38,0),
	t2.data:updated_at::VARCHAR,
	t2.data:user_id::VARCHAR,
	t2.data:billing_address::VARIANT,
	t2.data:customer::VARIANT,
	t2.data:discount_applications::VARIANT,
	t2.data:fulfillments::VARIANT,
	t2.data:line_items::VARIANT,
	t2.data:payment_terms::VARCHAR,
	t2.data:refunds::VARIANT,
	t2.data:shipping_address::VARIANT,
	t2.data:shipping_lines::VARIANT,
	t2.data:brand_code::VARCHAR)
"""
line_items_table_create = """
CREATE TABLE IF NOT EXISTS IAMCURIOUS_{env}.SHOPIFY_ORDER_LINE_ITEMS (
	id NUMBER(38,0),
    order_id NUMBER(38,0),
	admin_graphql_api_id VARCHAR,
	fulfillable_quantity NUMBER(38,0),
	fulfillment_service VARCHAR,
	fulfillment_status VARCHAR,
	gift_card BOOLEAN,
	grams NUMBER(38,0),
	name VARCHAR,
	origin_location VARIANT,
	price VARCHAR,
	price_set VARIANT,
	product_exists BOOLEAN,
	product_id NUMBER(38,0),
	properties VARIANT,
	quantity NUMBER(38,0),
	requires_shipping BOOLEAN,
	sku VARCHAR,
	taxable BOOLEAN,
	title VARCHAR,
	total_discount VARCHAR,
	total_discount_set VARIANT,
	variant_id NUMBER(38,0),
	variant_inventory_management VARCHAR,
	variant_title VARCHAR,
	vendor VARCHAR,
	tax_lines VARIANT,
	duties VARIANT,
	discount_allocations VARIANT
);
"""
line_items_upsert = """
MERGE INTO IAMCURIOUS_{env}.SHOPIFY_ORDER_LINE_ITEMS t1
   USING (
        select data:id as order_id, t0.value:id::NUMBER(38,0) as id, t0.value:admin_graphql_api_id::VARCHAR as admin_graphql_api_id, t0.value:fulfillable_quantity::NUMBER(38,0) as fulfillable_quantity, t0.value:fulfillment_service::VARCHAR as fulfillment_service, t0.value:fulfillment_status::VARCHAR as fulfillment_status, t0.value:gift_card::BOOLEAN as gift_card, t0.value:grams::NUMBER(38,0) as grams, t0.value:name::VARCHAR as name, t0.value:origin_location::VARIANT as origin_location, t0.value:price::VARCHAR as price, t0.value:price_set::VARIANT as price_set, t0.value:product_exists::BOOLEAN as product_exists, t0.value:product_id::NUMBER(38,0) as product_id, t0.value:properties::VARIANT as properties, t0.value:quantity::NUMBER(38,0) as quantity, t0.value:requires_shipping::BOOLEAN as requires_shipping, t0.value:sku::VARCHAR as sku, t0.value:taxable::BOOLEAN as taxable, t0.value:title::VARCHAR as title, t0.value:total_discount::VARCHAR as total_discount, t0.value:total_discount_set::VARIANT as total_discount_set, t0.value:variant_id::NUMBER(38,0) as variant_id, t0.value:variant_inventory_management::VARCHAR as variant_inventory_management, t0.value:variant_title::VARCHAR as variant_title, t0.value:vendor::VARCHAR as vendor, t0.value:tax_lines::VARIANT as tax_lines, t0.value:duties::VARIANT as duties, t0.value:discount_allocations::VARIANT as discount_allocations
        from IAMCURIOUS_{env}_STAGING.shopify_orders_temp orders,
        LATERAL flatten(input => orders.data:line_items) as t0
    )t2
    ON t1.id = t2.id
    when matched then update set 	t1.order_id = t2.order_id,
	t1.id = t2.id,
	t1.admin_graphql_api_id = t2.admin_graphql_api_id,
	t1.fulfillable_quantity = t2.fulfillable_quantity,
	t1.fulfillment_service = t2.fulfillment_service,
	t1.fulfillment_status = t2.fulfillment_status,
	t1.gift_card = t2.gift_card,
	t1.grams = t2.grams,
	t1.name = t2.name,
	t1.origin_location = t2.origin_location,
	t1.price = t2.price,
	t1.price_set = t2.price_set,
	t1.product_exists = t2.product_exists,
	t1.product_id = t2.product_id,
	t1.properties = t2.properties,
	t1.quantity = t2.quantity,
	t1.requires_shipping = t2.requires_shipping,
	t1.sku = t2.sku,
	t1.taxable = t2.taxable,
	t1.title = t2.title,
	t1.total_discount = t2.total_discount,
	t1.total_discount_set = t2.total_discount_set,
	t1.variant_id = t2.variant_id,
	t1.variant_inventory_management = t2.variant_inventory_management,
	t1.variant_title = t2.variant_title,
	t1.vendor = t2.vendor,
	t1.tax_lines = t2.tax_lines,
	t1.duties = t2.duties,
	t1.discount_allocations = t2.discount_allocations
    when not matched then insert values (
	t2.id,
	t2.order_id,
	t2.admin_graphql_api_id,
	t2.fulfillable_quantity,
	t2.fulfillment_service,
	t2.fulfillment_status,
	t2.gift_card,
	t2.grams,
	t2.name,
	t2.origin_location,
	t2.price,
	t2.price_set,
	t2.product_exists,
	t2.product_id,
	t2.properties,
	t2.quantity,
	t2.requires_shipping,
	t2.sku,
	t2.taxable,
	t2.title,
	t2.total_discount,
	t2.total_discount_set,
	t2.variant_id,
	t2.variant_inventory_management,
	t2.variant_title,
	t2.vendor,
	t2.tax_lines,
	t2.duties,
	t2.discount_allocations)
"""
